-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 12:10:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PHARMATIVE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PHARMATIVE` ;

-- -----------------------------------------------------
-- Schema PHARMATIVE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PHARMATIVE` DEFAULT CHARACTER SET utf8 ;
USE `PHARMATIVE` ;

-- -----------------------------------------------------
-- Table `PHARMATIVE`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`Brands` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`Categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`OrderItem` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `PHARMATIVE`.`Products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`OrderStatus` (
  `order_status_id` INT NOT NULL AUTO_INCREMENT,
  `order_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`order_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_item_id` INT NOT NULL,
  `order_status_id` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `order_status_id_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `user_id_101`
    FOREIGN KEY (`user_id`)
    REFERENCES `PHARMATIVE`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_status_id`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `PHARMATIVE`.`OrderStatus` (`order_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_item_id`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `PHARMATIVE`.`OrderItem` (`order_item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`Products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `product_title` VARCHAR(45) NOT NULL,
  `product_desc` VARCHAR(500) NOT NULL,
  `product_stock` INT NOT NULL,
  `product_price` INT NOT NULL,
  `featured` INT NULL,
  `brand_id` INT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `PHARMATIVE`.`Categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `PHARMATIVE`.`Brands` (`brand_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`ShippingAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`ShippingAddress` (
  `shipping_address_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`shipping_address_id`),
  INDEX `user_id_103_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id_103`
    FOREIGN KEY (`user_id`)
    REFERENCES `PHARMATIVE`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(30) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `email_address` VARCHAR(80) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `PHARMATIVE`.`UserRoles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHARMATIVE`.`UserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHARMATIVE`.`UserRoles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
